### ISSUE TITLE
ParseFacebookUtilsV4 duplicate symbols for architecture armv7

### ISSUE THREAD

**Issue by ammoqq** [ParsePlatform/Parse-SDK-iOS-OSX#343]
I have swift 1.2, xcode 6.3.1 

Here is my Apple Mach-O-Linker error:

    duplicate symbol _llvm.cmdline in:
    /directory/Pods/ParseFacebookUtilsV4/libParseFacebookUtilsV4Lib.a(PFFacebookAuthenticationProvider.o)
    /directory/Pods/ParseFacebookUtilsV4/libParseFacebookUtilsV4Lib.a(PFFacebookUtils.o)
    duplicate symbol _llvm.embedded.module in:
    /directory/Pods/ParseFacebookUtilsV4/libParseFacebookUtilsV4Lib.a(PFFacebookAuthenticationProvider.o)
    /directory/Pods/ParseFacebookUtilsV4/libParseFacebookUtilsV4Lib.a(PFFacebookUtils.o)
    ld: 2 duplicate symbols for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

and my podfile looks like this: 

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'MycOoolApp' do

pod 'Parse'
pod 'ParseFacebookUtilsV4'

Could you help with the error ? its killing me, maybe its xcode version is too old ?
If I only pod Parse the standard parse functions all work though, only when i add ParseFacebookUtilsV4 i get the error.

**Comment by nlutsenko** [comment]
Hey @ammoqq, thanks for the report!
This sounds quite strange, since we tested on both Xcode 7 and 6.4 (latest and previous versions) and it seems to work great.

I would really recommend using Xcode 7 (which is the latest public release), but you can use Xcode 6.4 if you don't want to update your project for Swift 2 just yet.

Let me know if this works on 6.4 in your case.
The other possibility that I think we can test is removing `use_frameworks!` if you don't really care whether you are shipping with dynamic frameworks or embedding static frameworks into your code.

**Comment by Parsida** [comment]
I have the same problem but with Xcode 6.4. 

The issue has been reported on SO as well: http://stackoverflow.com/questions/32783938/parsefacebookutilsv4-duplicate-symbols-for-architecture-armv7

**Comment by Parsida** [comment]
In my case, it's only building for the device that fails. There are some potential workarounds here: https://github.com/bitstadium/HockeySDK-iOS/issues/190

I've tried cleaning the project and the derived data. The error persists. I'll try the other suggestions later.

**Comment by ammoqq** [comment]
If you find how to solve it please share

**Comment by hoangcanhsek6** [comment]
I have the same problem in Xcode 6.4, If you solved it please share
Thanks.

**Comment by katopz** [comment]
@Parsida @ammoqq @hoangcanhsek6 I post my answer here http://stackoverflow.com/questions/32783938/parsefacebookutilsv4-duplicate-symbols-for-architecture-armv7

it work for me (happen to me yesterday)

**Comment by Parsida** [comment]
Thanks @katopz. I had the option to upgrade to Xcode 7. It worked out flawlessly.
