### ISSUE TITLE
Investigate bitcode support for the SDK.

### ISSUE THREAD

**Issue by richardjrossiii** [ParsePlatform/Parse-SDK-iOS-OSX#75]
In iOS 9, Apple is adding the ability for binaries to ship Bitcode (LLVM IR) slices alongside their binary. Currently, Parse doesn't support this.

This task will be the master task for investigating the requirements bitcode has on our code-base, and determining whether or not we should focus on Bitcode support in the SDK.

**Comment by richardjrossiii** [comment]
After extensive investigating, it would appear that adding bitcode support for Parse is a valuable effort, and is relatively simple to do.

 - It should require no code-changes, only a few minor build settings changes.
 - We will need to coordinate with [Bolts](https://github.com/boltsframework/Bolts-iOS) to ensure that we have bitcode support for that project.
 - We will need to enable Thumb support for our binaries (disabled in `Configurations/Shared/Platforms/iOS.xcconfig`)
 - We will need to **disable** the built-in Xcode setting for generating bitcode (`ENABLE_BITCODE`), as it will only generate bitcode markers unless building for an archive release, which is not done with the SDK.
 - We will need to add the `-fembed-bitcode` compile flag to the SDK, which will then being generating bitcode alongside the rest of our binaries.

A few possible downsides:

 - Enabling bitcode will significantly increase binary size, in my tests we see about 2X larger sizes. 
 - Enabling thumb may slightly (*read: unnoticeable*) performance reductions, specifically regarding floating-point, for explanation see [this StackOverflow answer](http://stackoverflow.com/questions/8390606/is-there-a-way-to-compile-for-arm-rather-than-thumb-in-xcode-4).

**Comment by nlutsenko** [comment]
Further investigation results:
- Compiling with `-fembed-bitcode` works on both `iphoneos9.0` and `iphonesimulator` SDKs
- After `lipo`ing both binaries together to get a fat binary - linking will fail on Xcode 6.4 with duplicate symbols, everything will work on Xcode 7.
- That problem can be fixed by removing `-fembed-bitcode` for `iphonesimulator` slices, which doesn't seem to break Xcode 7 and end-binary support for bitcode, as well as this works on Xcode 6.4.
- If the static binary has debug symbols - they should be either stripped or `CLANG_ENABLE_MODULES_DEBUGGING` should be disabled, or it is going to emit crazy amount of warnings for every `.o` inside the binary.

Implementation details:
- Add `-fembed-bitcode` to xcconfig only for `iphoneos9.0` SDK only
- Make sure `Deployment Postprocessing` is enabled
- Set `Strip Style` to `Debug Symbols` or higher
- Test on both Xcode 6.4 and Xcode 7 (latest beta or GM) building for Simulator, Device and Archiving.

**Comment by kostiakoval** [comment]
How bout ParseFacebookUtilsV4 lib? It does'n support bitcode as well.

**Comment by nlutsenko** [comment]
All of this would apply for ParseFacebookUtilsV4, ParseUI, ParseTwitterUtils as well as Bolts.
The only thing to note - we are aiming to support Bitcode the moment Xcode 7 GM is available, since LLVM IR (that's what Bitcode is) is changing with every llvm/clang release and won't be compatible between them.

Also, we are planning to opensource ParseFacebookUtils and ParseTwitterUtils, so you will be able to compile from source, where if you are using Cocoapods will automatically switch back and forth between bitcode, depending on your target.

**Comment by kostiakoval** [comment]
Great news, thanks!!!

**Comment by obastemur** [comment]
@nlutsenko thanks for the tip on xcode 6.4 issue. 

Side note: 
1 - `-fno-standalone-debug` kicks in prior to bitcode embedding hence reduces the generated bitcode / binary size.
2 - If anyone wonders why `strip` no longer works after `-fembed-bitcode`: Actually it does. The problem is the generated data can't be stripped using that tool.
