### ISSUE TITLE
Duplicate Symbols with ParseCrashReporting 1.8.3/4

### ISSUE THREAD

**Issue by levigroker** [ParsePlatform/Parse-SDK-iOS-OSX#271]
With ParseCrashReporting 1.8.3 & 1.8.4 (okay on 1.8.2) I'm now seeing duplicate symbol errors durring the linker phase when building for device.

ParseCrashReporting is installed via CocoaPods 0.38.2.

Mac OS X 10.11, Xcode 6.4, iOS 8.4 base SDK with iOS 7.0 deployment target.

	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(GTMLogger.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(GTMLogger.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(HTTPMultipartUpload.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(HTTPMultipartUpload.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(uploader.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(uploader.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(BreakpadController.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(BreakpadController.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(ParseCrashReporting.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(ParseCrashReporting.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReportingAnalytics.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReportingAnalytics.o)
	duplicate symbol _llvm.cmdline in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReport.o)
	duplicate symbol _llvm.embedded.module in:
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReporter.o)
		[redacted]/ParseCrashReporting/libParseCrashReportingLib.a(PFCrashReport.o)
	ld: 14 duplicate symbols for architecture arm64
	clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nlutsenko** [comment]
Hey @levigroker, thanks for the report.
This appears to be an issue with Xcode 6.4 specifically. 
Fix is incoming shortly, but in the meantime I would suggest you use Xcode 7 (it's already live on Mac App Store).

**Comment by levigroker** [comment]
Thanks @nlutsenko. I can't use Xcode 7 just yet, so I've just had to downgrade to 1.8.2 for now.

**Comment by nlutsenko** [comment]
Hey @levigroker, we don't seem to reproduce the problem as of right now on Xcode 6.4 (via Cocoapods and outside of Cocoapods).

Any chance you can provide a repro for this, so it's ultimately fixed for anyone running Xcode 6.4?

**Comment by levigroker** [comment]
Hi @nlutsenko I don't have time to prep a reproducible project for you at the moment, but I'm not the only one experiencing this: http://stackoverflow.com/questions/32612353/apple-mach-o-linker-error-after-updating-to-parse-1-8-4-pod

Thanks,
Levi

**Comment by nlutsenko** [comment]
Hey guys, we just shipped 1.8.5.
We still can't reproduce this in any way... 
But since that one has a purely recompiled framework using latest Xcode 7 - it might have made a difference for you.
Try it out and let us know if it works for you on Xcode 6.4

**Comment by levigroker** [comment]
Hi @nlutsenko, thanks for the update. Unfortunately it does not address the linker issue. :/

On the plus side, I have more information for you!

First, it seems to only affect the *test* target and only when building for device.

I've reproduced the problem in a "vanilla" project here:

https://www.dropbox.com/s/rse7ovcsrupog9f/ParseLinkerIssue.zip

The issue appears to be related to including the Pods.*.xcconfig in the test target configuration (see screenshot)
![screenshot](https://cloud.githubusercontent.com/assets/243505/10022840/1caead1a-610c-11e5-81d4-526cc2b36fc7.png)

It does not appear to be related to the target OS (the sample project is targeted at 8.4), but I did not test with Xcode 7 (only 6.4).

I hope this helps.

Cheers,

Levi

**Comment by levigroker** [comment]
What other information do you need?

**Comment by nlutsenko** [comment]
Hey @levigroker, we just released new version of Parse SDK and Parse Crash Reporting.
Could you try testing it on Xcode 6.4?

**Comment by gautamMoEngage** [comment]
I am pretty sure this is an issue with Xcode 6.4 compatibility with SDK's that are built with Bitcode support, aka Xcode 7. 

The duplicate symbol issues are because bitcode SDK's generate multiple copies for different architectures. Anything less than Xcode 7 won't work.

@levigroker - Try an older version of the SDK. I assure you it will work. I also assure you, the latest version won't work on Xcode 6.4, because I don't think Parse guys are making it without bitcode, which seems fair given that Apple does not allow watch OS support for SDK's that don't have bitcode support. @nlutsenko can confirm.

**Comment by nlutsenko** [comment]
Yup, @gautamMoEngage is absolutely right!

Even though we are trying to support Xcode 6.4 at all costs, the pre-built binaries indeed include bitcode and will likely to produce a linker error about duplicate symbols.
It all comes down to a simple fact that we always want support for the latest Xcode, latest iOS/SDK version... Which in this case, brakes compatibility with Xcode 6.4 (iOS7,8 still supported though, no breakage there).

**Comment by levigroker** [comment]
@gautamMoEngage Thanks... as I noted originally, older versions of the SDK do work.
@nlutsenko Thanks for your efforts on this. Our need to use Xcode 6.4 has passed, so I've moved on to Xcode 7, where I expect things will be fine, but I won't be able to test this for you.

**Comment by nlutsenko** [comment]
Hey guys, we've decided to deprecate our Crash Reporting product. We sent out an email to active users of Parse Crash Reporting last year. Here is a copy of that email:

---

Update to Parse Crash Reporting

Hi there,

At Parse, we're always working to improve your developer experience. Last December, we launched Parse Crash Reporting with the goals of recognizing, tracking, and ultimately resolving crashes in your app.

In the time since, we've seen huge strides being made within the industry's native solutions. These native experiences have the advantage of being more tightly integrated into your build and release process, offering a more robust, streamlined, and frictionless development experience for you.

The Parse Crash Reporting tool is now being deprecated in favor of these great native solutions. We will continue supporting Parse Crash Reporting until March 1, 2016.

Here's how you can smoothly switch from Parse Crash Reporting to Apple or Google's offerings:

Apple Docs
Google Docs
We're constantly tackling new challenges to help you build better than ever before. Please reach out if you have any questions or concerns to community@parse.com.

The Parse Team
