### ISSUE TITLE
Issues on iOS9: canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"

### ISSUE THREAD

**Issue by wangbourne** [ParsePlatform/Parse-SDK-iOS-OSX#188]
As titled, this issue is only related to iOS9:

Bug description:
Running warnning
canOpenURL: failed for URL: "cydia://" - error: "This app is not allowed to query for scheme cydia"

I can confirm it's a bug in Parse SDK since it's OK when I removed the SDK from my project. 

Thanks

**Comment by nlutsenko** [comment]
Hey @wangbourne, it actually was a bug in ParseCrashReporting, not the SDK itself.
I can confirm that this was fixed since v1.8.0 of the SDK (current latest is 1.8.2)
Any chance you can be using an old version?

**Comment by wangbourne** [comment]
@nlutsenko 
no, that's not the truth, I did the following test:
1. replace ParseCrashReporting.framework with 1.8.2(downloaded from Parse.com this morning) and run my project,  there still exists issue
2. remove all Parse related files(ParseCrashReporting.framework,Parse.framework and Bolts.framework) from my project, and run my project, it's OK

**Comment by nlutsenko** [comment]
It was a bug in the code in Parse SDK itself, that surfaced only in ParseCrashReporting since that code path was called only from there.
Did you update Parse.framework to the latest `1.8.2` as well?

**Comment by wangbourne** [comment]
I have been using Parse SDK for a long time. I would not like to upgrade Parse.framework since your updates often make things more complicated (please forgive me say so): failed to compile, etc.

Anyway, I have updated all three .frameworks to 1.8.2 and come an compile error as what I could expect :) 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BFCancellationTokenSource", referenced from:
      objc-class-ref in Parse(PFQuery.o)
      objc-class-ref in Parse(PFFile.o)
ld: symbol(s) not found for architecture x86_64

:)

**Comment by nlutsenko** [comment]
And that one suggests that you are missing the latest version of Bolts - 1.2.1. 
I would really recommend using Cocoapods since the installation/update experience there is much better.

**Comment by wangbourne** [comment]
You are right and the cydia issue is going after installing latest SDK.
Thanks so much :)

**Comment by nlutsenko** [comment]
:+1: Happy to help.

**Comment by SCLDev** [comment]
Does anyone know why this bug was there? Interested to know as I'm looking for a way to prevent jailbroken devices to be able to run my app? 

Many thanks

**Comment by MikhailPorechenkov68** [comment]
Please remove SplunkMint-iOS SDK from your project
